### ISSUE TITLE
All files removed after running npm run setup:fem

### ISSUE THREAD

**Issue by beardedtim** [kentcdodds/es6-todomvc#10]
What I did:
- Installed`nvm` and switched to `v6` which was confirmed both by `command -v nvm`, running `nvm install node`, and then running `nvm ls` which showed me that it was running `v6`
- created a new directory inside of my `code` folder,  ran `git clone https://github.com/kentcdodds/starwars-names.git`
- `cd` into that directory
- Then, following the instructions on the email, ran `npm run setup:fem`

What I expected to happen:
- For the package to be installed
- That when I went to `http://localhost:8080` for a ToDo app to be there

What actually happened:
- Console output:

```
> starwars-names@0.0.0-semantically-released setup:fem /Users/admin/Code/Front End Masters/starwars-names
> git checkout FEM/00-scratch

Branch FEM/00-scratch set up to track remote branch FEM/00-scratch from origin.
Switched to a new branch 'FEM/00-scratch'
```

running `ls` inside of the folder now shows nothing while before the `npm run setup:fem` gave me:

```
CONTRIBUTING.md         other                   webpack.config.babel.js
LICENSE                 package.json
README.md               src
```

**Comment by kentcdodds** [comment]
Hi @beardedtim, I think that you cloned the wrong repo. Maybe the email you received was incorrect, but if you're attending the Webpack workshop, you'll want to make sure that you're cloning this repo: `https://github.com/kentcdodds/es6-todomvc.git`

But beware of [this issue](https://github.com/kentcdodds/es6-todomvc/issues/9). I'm working on it now :)

**Comment by kentcdodds** [comment]
Alrighty, I think I've fixed it. Could you try a fresh clone?

**Comment by kentcdodds** [comment]
And make sure that you're cloning the correct repo :) Thanks for trying things out and reporting this issue!

**Comment by beardedtim** [comment]
@kentcdodds Ah, of course. I am attending both and got the repos mixed up on my browser, my mistake! You can tell it's a Friday after a long week!

After installing from the _correct_ repo, it all works! I am very sorry for opening this in the wrong repo.

**Comment by kentcdodds** [comment]
I'm thrilled that you're attending both and that it's working for you now! See you next week! Have a nice weekend :)
