### ISSUE TITLE
localhost - Site cannot be reached

### ISSUE THREAD

**Issue by cdelstad** [kentcdodds/es6-todomvc#12]
I am seeing these issues:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

Also another error at the end of the log file below when I tried to run npm start.
I am running Windows 10, 64bit.
node v6.3.1
npm  v3.10.3
git v2.9.2
[npm_log.txt](https://github.com/kentcdodds/es6-todomvc/files/405919/npm_log.txt)

**Comment by ghost** [comment]
logfile output attached. 
Windows 10 64 bit 
git version 2.8.1.windows.1
node v6.3.1
npm 3.10.3
[kcdoutput.txt](https://github.com/kentcdodds/es6-todomvc/files/405980/kcdoutput.txt)

**Comment by kentcdodds** [comment]
Hi friends! Thank you for reporting this. Unfortunately, the instructions I had them send to you were wrong. Copy/paste error on my part. The bit about `npm start` and `localhost:8080` were for my webpack workshop (today). If you were able to get to this point without error, then you're good.

As for the warnings you're seeing @cdelstad, those are probably fine. If your `setup:fem` command doesn't show any errors, then you're good :)

**Comment by cdelstad** [comment]
I don't see a Todo app - is that part of the webpack instructions as well?

**Comment by kentcdodds** [comment]
Yes it is.. 😅 sorry about that!

**Comment by piyalidey** [comment]
In my case, setup:fem ran just fine without giving any errors. However, I can not open localhost:8080. It says 'Connection Refused'.

**Comment by kentcdodds** [comment]
Yeah, sorry, you should have received an updated email indicating that the `localhost` bit was a mistake. You're good to go!
