### ISSUE TITLE
Cannot Remove "babel-plugin-transform-es2015-modules-commonjs"

### ISSUE THREAD

**Issue by wlingke** [kentcdodds/es6-todomvc#13]
Hey - I am also having this issue - same as #9. Except it's on the egghead series. I've also tried cloning the master branch and doing `npm install` then `npm run validate` but that also gives the error

**Comment by kentcdodds** [comment]
Yeah, I still need to update things with a recent breaking change with babel. For now, you can swap out `babel-preset-es2015-webpack` with `babel-preset-es2015` with configuration like this: https://github.com/kentcdodds/es6-todomvc/compare/FEM/03.0-es6ify...FEM/04.0-tree-shaking
