### ISSUE TITLE
setup:fem: `git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by nawrasbaghdadi** [kentcdodds/es6-todomvc#14]
I'm using mac this is what i get when running `npm run setup:fem`

```
npm ERR! Darwin 15.5.0
 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "validate"
 npm ERR! node v5.2.0
 npm ERR! npm  v3.5.2
 npm ERR! code ELIFECYCLE
 npm ERR! @ validate: `npm-run-all --parallel lint build test`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the @ validate script 'npm-run-all --parallel lint build test'.
 npm ERR! Make sure you have the latest version of node.js and npm installed.
 npm ERR! If you do, this is most likely a problem with the  package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     npm-run-all --parallel lint build test
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs 
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR!     npm owner ls 
 npm ERR! There is likely additional logging output above.
```

**Comment by kentcdodds** [comment]
Could you give me a little more of the output please? This output doesn't tell me enough to help you.

**Comment by nawrasbaghdadi** [comment]
this is the full terminal output after running the command 
' npm run setup:fem

> @ setup:fem /webback/es6-todomvc
> git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist  coverage && git checkout FEM/00-original-project

 Switched to branch 'FEM/07.1-deploy-surge'
 Your branch is up-to-date with 'origin/FEM/07.1-deploy-surge'.
 npm WARN eslint-loader@1.3.0 requires a peer of eslint@>=1.6.0 <3.0.0 but none was installed.
 npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.

> @ validate /webback/es6-todomvc
> npm-run-all --parallel lint build test
> 
> @ lint /webback/es6-todomvc
> eslint .
> 
> @ prebuild /webback/es6-todomvc
> rimraf dist
> 
> @ test /webback/es6-todomvc
> karma start
> 
> @ build /webback/es6-todomvc
> webpack --env.prod -p

 08 08 2016 20:46:38.172:ERROR [config]: Invalid config file!
  SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/webback/es6-todomvc/karma.conf.js:3:23)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.parseConfig (/webback/es6-todomvc/node_modules/karma/lib/config.js:307:22)
    at new Server (/webback/es6-todomvc/node_modules/karma/lib/server.js:56:20)

 npm ERR! Darwin 15.5.0
 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "test"
 npm ERR! node v5.2.0
 npm ERR! npm  v3.5.2
 npm ERR! code ELIFECYCLE
 npm ERR! @ test: `karma start`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the @ test script 'karma start'.
 npm ERR! Make sure you have the latest version of node.js and npm installed.
 npm ERR! If you do, this is most likely a problem with the  package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     karma start
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs 
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR!     npm owner ls 
 npm ERR! There is likely additional logging output above.

 npm ERR! Please include the following file with any support request:
 npm ERR!     /webback/es6-todomvc/npm-debug.log
 ERROR: "test" exited with 1.

 npm ERR! Darwin 15.5.0
 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "validate"
 npm ERR! node v5.2.0
 npm ERR! npm  v3.5.2
 npm ERR! code ELIFECYCLE
 npm ERR! @ validate: `npm-run-all --parallel lint build test`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the @ validate script 'npm-run-all --parallel lint build test'.
 npm ERR! Make sure you have the latest version of node.js and npm installed.
 npm ERR! If you do, this is most likely a problem with the  package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     npm-run-all --parallel lint build test
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs 
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR!     npm owner ls 
 npm ERR! There is likely additional logging output above.

 npm ERR! Please include the following file with any support request:
 npm ERR!     /webback/es6-todomvc/npm-debug.log

 npm ERR! Darwin 15.5.0
 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup:fem"
 npm ERR! node v5.2.0
 npm ERR! npm  v3.5.2
 npm ERR! code ELIFECYCLE
 npm ERR! @ setup:fem: `git checkout FEM/07.1-deploy-surge && npm install && npm run validate  && rimraf dist coverage && git checkout FEM/00-original-project`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the @ setup:fem script 'git checkout FEM/07.1-deploy-surge && npm install &&    npm run validate && rimraf dist coverage && git checkout FEM/00-original-project'.
 npm ERR! Make sure you have the latest version of node.js and npm installed.
 npm ERR! If you do, this is most likely a problem with the  package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf  dist coverage && git checkout FEM/00-original-project
 npm ERR! You can get information on how to open an issue for this project with:
  npm ERR!     npm bugs 
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR!     npm owner ls 
 npm ERR! There is likely additional logging output above.

 npm ERR! Please include the following file with any support request:
 npm ERR!     /webback/es6-todomvc/npm-debug.log
'

**Comment by kentcdodds** [comment]
Looks like you're using Node version 5. For this workshop you'll need Node version 6 installed. I recommend managing your Node version with [nvm](http://git.io/nvm)

**Comment by nawrasbaghdadi** [comment]
thanks that solved the issue

**Comment by alexzaizar09** [comment]
I am taking this same course and getting this error:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup:fem' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'presetup:fem', 'setup:fem', 'postsetup:fem' ]
5 info lifecycle @~presetup:fem: @
6 info lifecycle @~setup:fem: @
7 verbose lifecycle @~setup:fem: unsafe-perm in lifecycle true
8 verbose lifecycle @~setup:fem: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;A:\WorkingOn\LearningWebpack\FrontendMasters\es6-todomvc\node_modules\.bin;C:\Program Files\cmder\bin;C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Program Files\cmder\vendor\conemu-maximus5;C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Anaconda3;C:\Program Files\Anaconda3\Scripts;C:\Program Files\Anaconda3\Library\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\alex\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\alex\AppData\Local\Programs\Python\Python36-32\;C:\Users\alex\AppData\Local\Microsoft\WindowsApps;C:\Users\alex\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\Program Files\cmder\
9 verbose lifecycle @~setup:fem: CWD: A:\WorkingOn\LearningWebpack\FrontendMasters\es6-todomvc
10 silly lifecycle @~setup:fem: Args: [ '/d /s /c',
10 silly lifecycle   'git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project' ]
11 silly lifecycle @~setup:fem: Returned: code: 1  signal: null
12 info lifecycle @~setup:fem: Failed to exec setup:fem script
13 verbose stack Error: @ setup:fem: `git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid @
15 verbose cwd A:\WorkingOn\LearningWebpack\FrontendMasters\es6-todomvc
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup:fem"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ setup:fem: `git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project`
22 error Exit status 1
23 error Failed at the @ setup:fem script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

any help?
