### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by mgott** [kentcdodds/es6-todomvc#15]

**Comment by mgott** [comment]
npm error code: Cannot find module 'github-url-from-git'

**Comment by JDPelayoPetit** [comment]
I got "Error: Cannot find module 'npmlog'" on module.js:340

**Comment by kentcdodds** [comment]
Hi there, Could you give me a little more info please? I'm not sure how to help you.

**Comment by JDPelayoPetit** [comment]
Are you on a Mac? Did you installed node (and hence npm) through Homebrew, by any chance? I'm not sure if it's the case, but when you got npm through Homebrew, it can cause errors with globally installed packages. 

You can try the solution on this post >> https://gist.github.com/DanHerbert/9520689

Personally, I would simply uninstall Node and reinstall it altogether (just download the 6.3.1 version from nodejs.org). 

Hope this sheds some light on your problem.

**Comment by kentcdodds** [comment]
Thank you @JDPelayoPetit! You may also consider using [nvm](http://git.io/nvm)

**Comment by JDPelayoPetit** [comment]
That's even better @kentcdodds
