### ISSUE TITLE
failed to setup

### ISSUE THREAD

**Issue by ttpp8794** [kentcdodds/es6-todomvc#16]
TPHomeMac:starwars-names tphome$ npm run setup:fem

> starwars-names@0.0.0-semantically-released setup:fem /Users/tphome/starwars-names
> git checkout FEM/10.1-docs && npm install && npm run validate && rimraf .nyc_output coverage dist .git/hooks && git checkout FEM/00-scratch

Branch FEM/10.1-docs set up to track remote branch FEM/10.1-docs from origin.
Switched to a new branch 'FEM/10.1-docs'
(node:1386) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli

> fsevents@1.0.14 install /Users/tphome/starwars-names/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/tphome/starwars-names/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> execSync@1.0.2 install /Users/tphome/starwars-names/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> ghooks@1.3.2 install /Users/tphome/starwars-names/node_modules/ghooks
> node ./bin/module-install

**Comment by JoelMcKinnon** [comment]
Looks like I got a similar failure as ttpp8794:

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli

> fsevents@1.0.14 install /Users/joelmckinnon/Documents/workspace/starwars-names/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/joelmckinnon/Documents/workspace/starwars-names/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> execSync@1.0.2 install /Users/joelmckinnon/Documents/workspace/starwars-names/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

I end up with an impressive collection of node modules, but no web content and no server running on port 8080.

**Comment by kentcdodds** [comment]
So ya'll should have received an update stating that the instructions were incorrect about the `localhost:8080` bit. So if you saw output that looked like an npm install and some tests running (and passing) then you're good to go. Is that what you got?

**Comment by JoelMcKinnon** [comment]
That's what I have so I guess I'm good.

Joel
