### ISSUE TITLE
error with extract-text-webpack

### ISSUE THREAD

**Issue by lokky2082** [kentcdodds/es6-todomvc#31]
Hi i have this error, after start webpack --env.dev , what can i do with this ?
I would be grateful for help

ERROR in c:\es6-todomvc\node_modules\extract-text-webpack-plugin\loader.js?{"omit":1,"remove":true}!c:\es6-todomvc\node_modules\style-loader\index.js!c:\es6-todomvc\node_modules\css-loader\index.js!c:\es6-todomvc\node_modules\todomvc-app-css\index.css doesn't export content

ERROR in c:\es6-todomvc\node_modules\extract-text-webpack-plugin\loader.js?{"omit":1,"remove":true}!c:\es6-todomvc\node_modules\style-loader\index.js!c:\es6-todomvc\node_modules\css-loader\index.js!c:\es6-todomvc\node_modules\todomvc-app-css\index.css doesn't export content

ERROR in c:\es6-todomvc\node_modules\extract-text-webpack-plugin\loader.js?{"omit":1,"remove":true}!c:\es6-todomvc\node_modules\style-loader\index.js!c:\es6-todomvc\node_modules\css-loader\index.js!c:\es6-todomvc\src\app.css doesn't export content

**Comment by kentcdodds** [comment]
Hmmm... Could you verify you have the same versions as are in the workshop? Check the `package.json` and make sure your installed versions are the same. If you notice that there are differences from the workshop to the latest versions of any packages, please [makeapullrequest.com](http://makeapullrequest.com) to the README [Updates](https://github.com/kentcdodds/es6-todomvc#updates) section.

Other than that, I think your best bet is to make a question on StackOverflow. Good luck!
