### ISSUE TITLE
Dead Code Elimination doesn't work after Tree shaking

### ISSUE THREAD

**Issue by glrodasz** [kentcdodds/es6-todomvc#32]
I was looking into the `Tree shaking with Webpack 2 lesson`, and I took into account the `"presets": [["es2015", {modules: false}]]` change but when I run the `npm run build:prod` is not doing the dead code elimination. The addClass function is still there. Is it necessary any extra step?

I'm using the `lesson/treeshaking` branch and Node version `6.10.2`.

**Comment by kentcdodds** [comment]
Hi! I'm sorry, but I don't have time to help look into your problem right now. If you discover the solution please feel free to comment here with what it was. Good luck!

**Comment by glrodasz** [comment]
Sure, I will take a look.

**Comment by glrodasz** [comment]
Sorry, it is working. The problem is that when you use `webpack -p` is not showing the compress warnings anymore.

**Comment by kentcdodds** [comment]
Oh that's great! 🎉 

Would you like to add a note to explain that in the README?! :)
