### ISSUE TITLE
Bug: changing filter results in new `Todo` object being created, duplicating all state, resulting in incorrect render state

### ISSUE THREAD

**Issue by Domiii** [kentcdodds/es6-todomvc#39]
## Steps to reproduce:

1. Add a todo item
2. Go to "Completed" filter
3. Reload the page
3. Select "All"
4. Mark item as completed.
5. Observe bug: It won't show up anymore, even though we are in `All`.

Turns out, that is because we now have two `Todo` instances (one for each filter), and the one created for the `Completed` filter takes presedence. Meaning we see `Completed` (rather than `All`) Todos.

## What to do?

The bug comes from the fact that `onLoad` is called when switching between filters, which in turn calls `updateTodo`, which in turn creates a new `Todo` instance each time, and a copy of all state. It also re-registers all event handlers, which will render according to their own state.

Fix: Change `src/todo.js`, line 27 to `todo = todo || new Todo('todos-vanillajs');`, so it won't create another `Todo` instance, if one already exists.

**Comment by kentcdodds** [comment]
Hi @Domiii, thanks for the report. This repo should have been archived however since I'm not actively maintaining it. Feel free to fork it though!
