### ISSUE TITLE
Destructuring in webpack config throws error

### ISSUE THREAD

**Issue by bvarberg** [kentcdodds/es6-todomvc#5]
##### What happens

After cloning the workshop repo and checking out the `workshop/07-coverage` branch, running `npm run setup` exits with an error before testing and coverage completes.

I was still able to subsequently checkout the `workshop/00-original-project` branch and run `npm start` with no problems. However, any branch after that (as soon as webpack is introduced) will error on both `npm start` and `npm run validate`.
##### Why it happens

The `test` script (as part of the `validate` script) is throwing an error as a result of destructuring in the webpack configuration. As far as I know (read: as far as [node.green](http://node.green/) knows), Node doesn't support the destructuring unless you're using `v6.x` -- I'm running `v4.4.1` (this is the problem).
##### Why I'm even bringing it up

I just thought I'd let you know, since a specific Node version wasn't in the prep instructions for the workshop -- _and_ in the off-chance that you _do_ consider this an issue, and want to modify the configuration file or the instructions for future workshops. 
##### Quick fix for Node v4.x

Getting things to run as expected, without changing to `v6.x`:

``` js
// webpack.config.js

const {resolve} = require('path')
// becomes...
const resolve = require('path').resolve
```

Looking forward to the workshop!

**Comment by kentcdodds** [comment]
Thanks for letting me know! I did ask the organizers to send along instructions where I mention Node 6 is recommended. But I wasn't planning on making it required. I'm just so used to ES6. 😅

Thanks again. I'll update the branches tonight.

**Comment by kentcdodds** [comment]
Just fixed this, could you please verify? I tried it with v4 on my computer and it works great for me. Thanks again for letting me know!

**Comment by bvarberg** [comment]
Sorry, didn't see this until just now. Just went through the prep process again and everything works as expected. Thanks for clarifying!
